name: wanandroid_app
description: 使用wanandroid 开放api
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  logger: ^1.0.0
  flutter_swiper: ^1.1.6
  cookie_jar: ^3.0.1
  webview_flutter: ^2.0.12
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.2
  json_annotation: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon_flutter.png
    - images/hd_arrow_right.png
    - images/hd_gaoyuanyuan.jpg
    - images/hd_update_head.jpg
    - images/hd_white_close.png


