name: wanandroid_app
description: 使用wanandroid 开放api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  logger: ^1.0.0
  cached_network_image: ^3.2.0      # 图片加载
  card_swiper: ^2.0.3               # 轮播图  flutter_swiper太老，两者内容一样
  pull_to_refresh: ^2.0.0           # 下拉刷新上拉加载

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/common/

